WHITE = 0
RED = 1
GREEN = 2
ORANGE = 3
BLUE = 4
YELLOW = 5

COLORS = [WHITE, RED, GREEN, ORANGE, BLUE, YELLOW]

CONFIGURATIONS = {
    # (front, top): [back, bottom, left, right]     # n
    (RED, WHITE): [ORANGE, YELLOW, GREEN, BLUE],    # 1
    (BLUE, WHITE): [GREEN, YELLOW, RED, ORANGE],    # 2
    (ORANGE, WHITE): [RED, YELLOW, BLUE, GREEN],    # 3
    (GREEN, WHITE): [BLUE, YELLOW, ORANGE, RED],    # 4
    (RED, YELLOW): [ORANGE, WHITE, BLUE, GREEN],    # 5
    (GREEN, YELLOW): [BLUE, WHITE, RED, ORANGE],    # 6
    (ORANGE, YELLOW): [RED, WHITE, GREEN, BLUE],    # 7
    (BLUE, YELLOW): [GREEN, WHITE, ORANGE, RED],    # 8
    (WHITE, ORANGE): [YELLOW, RED, GREEN, BLUE],    # 9
    (BLUE, ORANGE): [GREEN, RED, WHITE, YELLOW],    # 10
    (YELLOW, ORANGE): [WHITE, RED, BLUE, GREEN],    # 11
    (GREEN, ORANGE): [BLUE, RED, YELLOW, WHITE],    # 12
    (WHITE, RED): [YELLOW, ORANGE, BLUE, GREEN],    # 13
    (GREEN, RED): [BLUE, ORANGE, WHITE, YELLOW],    # 14
    (YELLOW, RED): [WHITE, ORANGE, GREEN, BLUE],    # 15
    (BLUE, RED): [GREEN, ORANGE, YELLOW, WHITE],    # 16
    (WHITE, BLUE): [YELLOW, GREEN, ORANGE, RED],    # 17
    (RED, BLUE): [ORANGE, GREEN, WHITE, YELLOW],    # 18
    (YELLOW, BLUE): [WHITE, GREEN, RED, ORANGE],    # 19
    (ORANGE, BLUE): [RED, GREEN, YELLOW, WHITE],    # 20
    (WHITE, GREEN): [YELLOW, BLUE, RED, ORANGE],    # 21
    (ORANGE, GREEN): [RED, BLUE, WHITE, YELLOW],    # 22
    (YELLOW, GREEN): [WHITE, BLUE, ORANGE, RED],    # 23
    (RED, GREEN): [ORANGE, BLUE, YELLOW, WHITE]     # 24
}